NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Models/Slider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NaranjAcademicMagazine.Areas.Admin.Models
{
    public class Slider
    {
        public int id { get; set; }
        public string header { get; set; }
        public string body { get; set; }
        public HttpPostedFileBase image { get; set; }
        public string imageString { get; set; }
    }
}

NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using NaranjAcademicMagazine.Areas.Admin.Models;

namespace NaranjAcademicMagazine.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        // GET: Admin/Slider
        public ActionResult Index()
        {
            string query = "select * from Slider order by id desc";
            SqlConnectionClass con = new SqlConnectionClass();
            var dt = con.Select(query);
            return View(dt);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Slider slider)
        {
            string Name = Path.GetFileName(slider.image.FileName);

            if (slider.image != null && slider.image.ContentLength > 0)
            {
                string fileName = Path.GetFileName(slider.image.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Areas/Admin/UploadedFiles"), fileName);
                slider.image.SaveAs(filePath);
            }

            string query = string.Format("INSERT INTO Slider(header,body,image) VALUES('{0}','{1}','{2}')", slider.header, slider.body, Name);
            SqlConnectionClass obj = new SqlConnectionClass();
            obj.Insert(query);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            SqlConnectionClass con = new SqlConnectionClass();
            string selectQuery = "select * from Slider where id = " + id;
            var result = con.Select(selectQuery);
            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(Slider slider, int id)
        {

            string Name = Path.GetFileName(slider.image.FileName);
            if (slider.image != null && slider.image.ContentLength > 0)
            {
                string fileName = Path.GetFileName(slider.image.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Areas/Admin/UploadedFiles"), fileName);
                slider.image.SaveAs(filePath);
            }
            string query = "update Slider set header = '" + slider.header + "', body = '" + slider.body + "', image = '" + Name + "' where id = " + id;
            SqlConnectionClass obj = new SqlConnectionClass();
            obj.Update(query);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            string query = "Delete from Slider where id = " + id;
            SqlConnectionClass con = new SqlConnectionClass();
            con.Delete(query);

            return View();
        }
    }
}

NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/Slider/Create.cshtml
@model NaranjAcademicMagazine.Areas.Admin.Models.Slider
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}

<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Home")><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Slider")>Slider</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Add</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Add Slider -->
                <div class="card-header border-0">
                    <h3 class="mb-0" style="text-align:center; font-size: 24px;">Add Slider Details</h3>
                </div>
                <!-- Add Slider -->
                <div class="formContainer">
                    @using (Html.BeginForm("Create", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div>
                            <label for="header">Header</label>
                            <input type="text" id="header" name="header" />
                            <label for="body">Body</label>
                            <input type="text" id="body" name="body" rows="50" cols="50" />
                            <label for="image">Image</label>
                            <input type="file" id="image" name="image"/>
                        </div>
                        <input type="submit" value="Submit" />
                    }
                </div>

            </div>
        </div>
    </div>


NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/Slider/Delete.cshtml
@model NaranjAcademicMagazine.Areas.Admin.Models.Slider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainPageLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Slider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.header)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.header)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imageString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imageString)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/Slider/Edit.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}

<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Home")><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Slider")>Slider</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Edit Slider -->
                <div class="card-header border-0">
                    <h3 class="mb-0" style="text-align:center; font-size: 24px;">Edit Slider Details</h3>
                </div>
                <!-- Edit Slider -->
                <div class="formContainer">
                    @for (int i = 0; i < Model.Rows.Count; i++)
                    {
                        using (Html.BeginForm("Edit", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div>
                                <label for="title">Title</label>
                                <input type="text" id="title" name="title" value="@Model.Rows[i][1]" />
                                <label for="description">Description</label>
                                <input type="text" id="description" name="description" value="@Model.Rows[i][2]" />
                            </div>
                            <input type="submit" value="Save" />
                        }
                    }
                </div>

            </div>
        </div>
    </div>

NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/Slider/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Tables</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Home")><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Slider")>Slider</a></li>
                            <li class="breadcrumb-item active" aria-current="page">List</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 col-5 text-right">
                    <a href=@Url.Action("Create","Slider") class="btn btn-sm btn-neutral">Add</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header border-0">
                    <h3 class="mb-0">List of Slider</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="ID">ID</th>
                                <th scope="col" class="sort" data-sort="Title">Header</th>
                                <th scope="col" class="sort" data-sort="Description">Body</th>
                                <th scope="col" class="sort" data-sort="Description">Image</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        @for (int i = 0; i < Model.Rows.Count; i++)
                        {
                            <tbody class="list">
                                <tr>
                                    <td>
                                        @Model.Rows[i][0]

                                    </td>
                                    <td>
                                        @Model.Rows[i][1]

                                    </td>
                                    <td>
                                        @Model.Rows[i][2]
                                    </td>
                                    <td>
                                        @{
                                            string src = "~/Areas/Admin/UploadedFiles/" + @Model.Rows[i][3];
                                        }
                                        <img src="@Url.Content(src)" width="100" height="100" />
                                    </td>
                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item" href=@Url.Action("Edit", "Slider", new { @id = @Model.Rows[i][0] })>Edit</a>
                                                <a class="dropdown-item" href=@Url.Action("Delete", "Slider", new { @id = @Model.Rows[i][0] })>Delete</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        }
                    </table>
                </div>
                <!-- Card footer -->
                <div class="card-footer py-4">
                    <nav aria-label="...">
                        <ul class="pagination justify-content-end mb-0">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">
                                    <i class="fas fa-angle-left"></i>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">
                                    <i class="fas fa-angle-right"></i>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
