NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Models/EditorialBoard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NaranjAcademicMagazine.Areas.Admin.Models
{
    public class EditorialBoard
    {
        public int memberId { get; set; }
        public string memberName { get; set; }
        public string description { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string linkedIn { get; set; }
        public HttpPostedFileBase image { get; set; }
        public string phone { get; set; }
    }
}

NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Controllers/EditorialBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using System.Data.SqlClient;
using NaranjAcademicMagazine.Areas.Admin.Models;

namespace NaranjAcademicMagazine.Areas.Admin.Controllers
{
    public class EditorialBoardController : Controller
    {
        // GET: EditorialBoard
        public ActionResult Index()
        {
            SqlConnectionClass con = new SqlConnectionClass();
            var dt = con.Select("select * from EditorialBoard");
            return View(dt);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(EditorialBoard member)
        {
            string Name = Path.GetFileName(member.image.FileName);

            if (member.image != null && member.image.ContentLength > 0)
            {
                string fileName = Path.GetFileName(member.image.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Areas/Admin/UploadedFiles"), fileName);
                member.image.SaveAs(filePath);
            }
            string query = string.Format("INSERT INTO EditorialBoard(memberName,description,email,facebook,twitter,linkedIn,image,phone) VALUES('{0}','{1}','{2}','{3}','{4}','{5}','{6}','{7}')", member.memberName, member.description, member.email, member.facebook, member.twitter, member.linkedIn, Name, member.phone);
            SqlConnectionClass obj = new SqlConnectionClass();
            obj.Insert(query);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            SqlConnectionClass con = new SqlConnectionClass();
            string selectQuery = "select * from EditorialBoard where memberId = " + id;
            var result = con.Select(selectQuery);
            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(EditorialBoard member, int id)
        {
            string Name = Path.GetFileName(member.image.FileName);
            if (member.image != null && member.image.ContentLength > 0)
            {
                string fileName = Path.GetFileName(member.image.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Areas/Admin/UploadedFiles"), fileName);
                member.image.SaveAs(filePath);
            }
            string query = "update EditorialBoard set memberName = '" + member.memberName + "', description = '" + member.description + "', email = '" + member.email + "', facebook = '" + member.facebook + "', twitter = '" + member.twitter + "', linkedIn = '" + member.linkedIn + "', image = '" + Name + "', phone = '"+ member.phone +"' where memberId = " + id;
            SqlConnectionClass obj = new SqlConnectionClass();
            obj.Update(query);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            string query = "Delete from EditorialBoard where memberId = " + id;
            SqlConnectionClass con = new SqlConnectionClass();
            con.Delete(query);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult List(int id)
        {
            string query = "select * from EditorialBoard where memberId = " + id;
            SqlConnectionClass con = new SqlConnectionClass();
            var dt = con.Select(query);
            return View(dt);
        }
    }
}

NaranjAcademicMagazine/NaranjAcademicMagazine/Controllers/EditorialBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NaranjAcademicMagazine.Areas.Admin.Models;

namespace NaranjAcademicMagazine.Controllers
{
    public class EditorialBoardController : Controller
    {
        // GET: EditorialBoard
        public ActionResult Index()
        {
            SqlConnectionClass con = new SqlConnectionClass();
            var dt = con.Select("select * from EditorialBoard");
            return View(dt);
        }
    }
}

NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/EditorialBoard/Create.cshtml
@model NaranjAcademicMagazine.Areas.Admin.Models.EditorialBoard
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Home")><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","EditorialBoard")>Editorial Board</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Add</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Add Issue -->
                <div class="card-header border-0">
                    <h3 class="mb-0" style="text-align:center; font-size: 24px;">Add Member Details</h3>
                </div>
                <!-- Add Issue -->
                <div class="formContainer">
                    @using (Html.BeginForm("Create", "EditorialBoard", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div>
                            <label for="memberName">Name</label>
                            <input type="text" id="memberName" name="memberName" />
                            <label for="description">Description</label>
                            <input type="text" id="description" name="description" />
                            <label for="pass">Email</label>
                            <input type="email" id="email" name="email" />
                            <label for="phone">Phone</label>
                            <input type="text" id="phone" name="phone" />
                            <label for="pass">Facebook Link</label>
                            <input type="text" id="facebook" name="facebook" />
                            <label for="pass">Twitter</label>
                            <input type="text" id="twitter" name="twitter" />
                            <label for="pass">LinkedIn</label>
                            <input type="text" id="linkedIn" name="linkedIn" />
                            <label for="image">Image</label>
                            <input type="file" id="image" name="image" />
                        </div>
                        <input type="submit" value="Submit" />
                    }
                </div>

            </div>
        </div>
    </div>


NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/EditorialBoard/Delete.cshtml
@model NaranjAcademicMagazine.Areas.Admin.Models.EditorialBoard

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EditorialBoard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.memberId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.memberId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.memberName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.memberName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.facebook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.facebook)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.twitter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.twitter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.linkedIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.linkedIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/EditorialBoard/Edit.cshtml
@model System.Data.DataTable

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Home")><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","EditorialBoard")>Editorial Board</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Edit Issue -->
                <div class="card-header border-0">
                    <h3 class="mb-0" style="text-align:center; font-size: 24px;">Edit Member Details</h3>
                </div>
                <!-- Edit Issue -->
                <div class="formContainer">
                    @for (int i = 0; i < Model.Rows.Count; i++)
                    {
                        using(Html.BeginForm("Edit", "EditorialBoard", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div>
                                <label for="memberName">Name</label>
                                <input type="text" id="memberName" name="memberName" value="@Model.Rows[i][1]" />
                                <label for="description">Description</label>
                                <input type="text" id="description" name="description" value="@Model.Rows[i][2]" />
                                <label for="pass">Email</label>
                                <input type="email" id="email" name="email" value="@Model.Rows[i][3]" />
                                <label for="phone">Phone</label>
                                <input type="text" id="phone" name="phone" value="@Model.Rows[i][8]" />
                                <label for="pass">Facebook Link</label>
                                <input type="text" id="facebook" name="facebook" value="@Model.Rows[i][4]" />
                                <label for="pass">Twitter</label>
                                <input type="text" id="twitter" name="twitter" value="@Model.Rows[i][5]" />
                                <label for="pass">LinkedIn</label>
                                <input type="text" id="linkedIn" name="linkedIn" value="@Model.Rows[i][6]" />
                                <label for="image">Image</label>
                                <input type="file" id="image" name="image" value="@Model.Rows[i][7]" />
                            </div>
                            <input type="submit" value="Save" />
                        }
                    }
                </div>

            </div>
        </div>
    </div>


NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/EditorialBoard/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","Home")><i class="fas fa-home"></i></a></li>
                            <li class="breadcrumb-item"><a href=@Url.Action("Index","EditorialBoard")>Editorial Board</a></li>
                            <li class="breadcrumb-item active" aria-current="page">List</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 col-5 text-right">
                    <a href=@Url.Action("Create","EditorialBoard") class="btn btn-sm btn-neutral">Add</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                    <h3 class="mb-0">List of Members</h3>
                </div>
                <!-- Light table -->
                <div class="table-responsive">
                    <table class="table align-items-center table-flush"  style="margin-bottom:20px;">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="AuthorId">ID</th>
                                <th scope="col" class="sort" data-sort="Name">Name</th>
                                <th scope="col" class="sort" data-sort="Description">Description</th>
                                <th scope="col" class="sort" data-sort="Email">Email</th>
                                <th scope="col" class="sort" data-sort="Phone">Phone</th>
                                <th scope="col" class="sort" data-sort="Facebook">Facebook</th>
                                <th scope="col" class="sort" data-sort="LinkedIn">LinkedIn</th>
                                <th scope="col" class="sort" data-sort="Twitter">Twitter</th>
                                <th scope="col" class="sort" data-sort="Twitter">Image</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            @for (int i = 0; i < Model.Rows.Count; i++)
                            {
                            <tr>
                                <td>
                                    @Model.Rows[i][0]

                                </td>
                                <td>
                                    @Model.Rows[i][1]

                                </td>
                                <td>
                                    @Model.Rows[i][2]
                                </td>
                                <td>
                                    @Model.Rows[i][3]
                                </td>
                                <td>
                                    @Model.Rows[i][8]
                                </td>
                                <td>
                                    @Model.Rows[i][4]
                                </td>
                                <td>
                                    @Model.Rows[i][5]
                                </td>
                                <td>
                                    @Model.Rows[i][6]
                                </td>
                                <td>
                                    @{
                                        string src = "~/Areas/Admin/UploadedFiles/" + @Model.Rows[i][7];
                                    }
                                    <img src="@Url.Content(src)" width="100" height="100" />
                                </td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a class="dropdown-item" href=@Url.Action("Edit", "EditorialBoard", new { @id=@Model.Rows[i][0] })>Edit</a>
                                            <a class="dropdown-item" href=@Url.Action("Delete", "EditorialBoard", new { @id=@Model.Rows[i][0] })>Delete</a>
                                            <a class="dropdown-item" href=@Url.Action("List", "EditorialBoard", new { @id=@Model.Rows[i][0] })>View</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- Card footer -->
                <div class="card-footer py-4">
                    <nav aria-label="...">
                        <ul class="pagination justify-content-end mb-0">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">
                                    <i class="fas fa-angle-left"></i>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">
                                    <i class="fas fa-angle-right"></i>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>


NaranjAcademicMagazine/NaranjAcademicMagazine/Areas/Admin/Views/EditorialBoard/List.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "List";
    Layout = "~/Areas/Admin/Views/Shared/_MainPageLayout.cshtml";
}

    <div class="card-author" style="margin-top:30px;">
        @for (int i = 0; i < Model.Rows.Count; i++)
        {
            string src = "~/Areas/Admin/UploadedFiles/" + @Model.Rows[i][7];
            <img src="@Url.Content(src)" width="100" height="100" />
            @*<img src="~/Content/img/theme/profile-cover.jpg" alt="John" style="width:100%">*@
            <h1>@Model.Rows[i][1]</h1>
            <p class="title">@Model.Rows[i][2]</p>
            <p>@Model.Rows[i][3]</p>
            <p>@Model.Rows[i][8]</p>
            <div style="margin: 24px 0;">
                <span>@Model.Rows[i][4] </span><span>@Model.Rows[i][5] </span><span>@Model.Rows[i][6]</span>
            </div>
        }
    </div>
